name: wb_sign

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 8,23 * * * 
  watch:
    types: started
  
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
    - name: 签到       
      run: |
        sub='${{ secrets.SUB }}'
        Key='${{ secrets.KEY }}'
        push_type='${{ secrets.push_type }}'
       
       
        python index.py
